[package]
name = "jvoaq"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
latkerlo-jvotci = "2.2.0"
regex = "1.11.1"
reqwest = { version = "0.12.14", features = ["blocking"] }
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_json = "1.0.140"
